"""Analytics agent — computes the impact report with the LOCKED constants.

See docs/ARCHITECTURE.md → Canonical Constants. When persisting, only the base
columns are stored; `savings_km` and `savings_pct` are derived (generated by the
DB schema) and must not be inserted.
"""
from __future__ import annotations

from backend import db

CO2_PER_KM = 0.21        # kg CO2 per km (diesel)
INR_PER_KM = 8           # ₹ fuel cost per km
MIN_PER_KM = 2.4         # minutes saved per km
KG_CO2_PER_TREE = 21.77  # kg CO2 absorbed per tree per year


async def run(run_id: str, naive_km: float, optimised_km: float,
              deliveries_total: int, deliveries_on_time: int) -> dict:
    naive_km = float(naive_km or 0)
    optimised_km = float(optimised_km or 0)

    savings_km = max(naive_km - optimised_km, 0.0)
    savings_pct = (savings_km / naive_km * 100) if naive_km else 0.0
    co2 = savings_km * CO2_PER_KM
    cost = savings_km * INR_PER_KM
    time_min = savings_km * MIN_PER_KM
    on_time_rate = (deliveries_on_time / deliveries_total) if deliveries_total else 0.0
    trees = co2 / KG_CO2_PER_TREE

    report = {
        "naive_km": round(naive_km, 2),
        "optimised_km": round(optimised_km, 2),
        "savings_km": round(savings_km, 2),
        "savings_pct": round(savings_pct, 2),
        "co2_avoided_kg": round(co2, 2),
        "cost_saved_inr": round(cost, 2),
        "time_saved_min": round(time_min, 2),
        "on_time_rate": round(on_time_rate, 2),
        "trees_equivalent": round(trees, 2),
    }

    # Persist base columns only (savings_km / savings_pct are DB-generated).
    db.save_analytics(run_id, {k: v for k, v in report.items()
                               if k not in ("savings_km", "savings_pct")})
    db.set_run_status(run_id, "completed")
    db.log(run_id, "analytics",
           f"Impact: {report['savings_km']} km saved, {report['co2_avoided_kg']} kg CO2, "
           f"₹{report['cost_saved_inr']} saved ({report['trees_equivalent']} trees/yr)")
    return report
